services:
  fluent-bit:
    image: fluent/fluent-bit
    container_name: fluent-bit
    volumes:
      - ${SORA_LOG_PATH}:/log
      - ./fluent-bit.yml:/fluent-bit/etc/fluent-bit.yml
    networks:
      - kohaku
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    depends_on:
      - mc
    command: /fluent-bit/bin/fluent-bit -c /fluent-bit/etc/fluent-bit.yml

  # 外部 S3 互換ストレージ の初期設定用コンテナ
  mc:
    image: minio/mc:RELEASE.2025-07-21T05-28-08Z
    container_name: mc
    networks:
      - kohaku
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - S3_ENDPOINT=${S3_ENDPOINT}
      - S3_BUCKET=${S3_BUCKET}
      - S3_USE_SSL=${S3_USE_SSL:-true}
      - RETENTION_PERIOD=${RETENTION_PERIOD}
    volumes:
      - ./scripts/mc-init.sh:/scripts/mc-init.sh:ro
    entrypoint:
      - /bin/sh
      - /scripts/mc-init.sh

  # motherduck-duckdb-datasource は ./plugins に展開済みの想定
  grafana:
    image: grafana/grafana:12.4.3-ubuntu
    container_name: grafana
    ports:
      - ${GRAFANA_HTTP_PORT}:3000
    networks:
      - kohaku
    environment:
      - GF_LOG_MODE=console
      - GF_PATHS_DATA=/var/lib/grafana
      - GF_SECURITY_ADMIN_USER=${GF_SECURITY_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
      - GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS=motherduck-duckdb-datasource
      - GF_PATHS_HOME=/usr/share/grafana
      - GF_PATHS_CONFIG=/etc/grafana/grafana.ini
      - GF_PATHS_PLUGINS=/var/lib/grafana/plugins
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_PLUGINS_FORWARD_HOST_ENV_VARS=motherduck-duckdb-datasource
    volumes:
      - ./grafana/datasources:/etc/grafana/provisioning/datasources
      - ./grafana/dashboards/kohaku.yml:/etc/grafana/provisioning/dashboards/kohaku.yml
      - ./grafana/dashboards/kohaku:/var/lib/grafana/dashboards/kohaku
      - ./plugins/motherduck-duckdb-datasource:/var/lib/grafana/plugins/motherduck-duckdb-datasource
      - duckdb:/var/lib/kohaku

  ingester:
    build:
      context: ./ingester
      dockerfile: Dockerfile
    container_name: ingester
    environment:
      - DUCKDB_DB_PATH=${DUCKDB_DB_PATH}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - S3_ENDPOINT=${S3_ENDPOINT}
      - S3_USE_SSL=${S3_USE_SSL:-true}
      - S3_BUCKET=${S3_BUCKET}
      - S3_PREFIX=${S3_PREFIX}
      - INITIAL_MAXIMUM_LOAD=${INITIAL_MAXIMUM_LOAD:-100}
      - UPDATE_MAXIMUM_LOAD=${UPDATE_MAXIMUM_LOAD:-100}
      - UPDATE_INTERVAL=${UPDATE_INTERVAL}
      - RETENTION_PERIOD=${RETENTION_PERIOD}
    depends_on:
      - grafana
    networks:
      - kohaku
    volumes:
      - ./ingester:/ingester
      - ingester-venv:/ingester/.venv
      - duckdb:/var/lib/kohaku

volumes:
  ingester-venv:
    name: kohaku-ingester-venv
    driver: local
  duckdb:
    name: kohaku-volume
    driver: local

networks:
  kohaku:
    name: kohaku-network
    driver: bridge
