version: "3.9"
name: "kohaku-dev"

services:
  clickhouse:
    image: clickhouse/clickhouse-server:latest
    ports:
      - "8123:8123"
      - "9000:9000"

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3333:3000"
    volumes:
      - ./.grafana:/var/lib/grafana
      - ./grafana/datasources:/etc/grafana/provisioning/datasources
      - ./grafana/dashboards/kohaku.yml:/etc/grafana/provisioning/dashboards/kohaku.yml
      - ./grafana/dashboards/kohaku:/var/lib/grafana/dashboards/kohaku
    depends_on:
      - clickhouse
