debug = true

# Kohaku の HTTP リクエストで HTTPS を利用するかどうか
https = false
# Kohaku の HTTP リクエストの待ち受けアドレスとポートです
listen_addr = 0.0.0.0
listen_port = 5890

exporter_https = false
# Kohaku の Prometheus の待ち受けアドレスとポートです
exporter_listen_addr = 0.0.0.0
exporter_listen_port = 5891

# kohaku のサーバ証明書ファイルです
# tls_fullchain_file =
# kohaku の秘密鍵ファイルです
# tls_privkey_file =
# クライアント認証用の CA 証明書ファイルです
# tls_verify_cacert_path =

# [log]
# ログの出力先ディレクトリです
log_dir = .
# ログの出力先ファイルのファイル名です
log_name = kohaku.jsonl
# ログの標準出力への出力可否の指定です
# true にした場合はファイルにログは出力されません
log_stdout = true

# ローテーションするログの最大サイズ（MB）です
#log_rotate_max_size = 200
# 保持するログファイルの最大数です
#log_rotate_max_backups = 7
# 古いログファイルを保持する最大日数です
#log_rotate_max_age = 30

# kohaku が利用する ClickHouse の Addr を 192.0.2.1:9000 のように指定してください
clickhouse_addr = 192.0.2.1:9000

clickhouse_database = default
clickhouse_username = default
clickhouse_passowrd = default
# kohaku が利用する ClickHouse の CA 証明書ファイルです
# clickhouse_ca_cert_file = cert/postgres/ca.pem

# clickhouse_debug = true