debug = true

# Kohaku の HTTP リクエストの待ち受けアドレスとポートです
https = true
listen_addr = 0.0.0.0
listen_port = 5890

exporter_https = false
exporter_listen_addr = 0.0.0.0
exporter_listen_port = 5891

# kohaku のサーバ証明書ファイルです
tls_fullchain_file = cert/server/server.pem
# kohaku の秘密鍵ファイルです
tls_privkey_file = cert/server/server.key
# クライアント認証用の CA 証明書ファイルです
# tls_verify_cacert_path = cert/server/ca.pem

# [log]
# ログの出力先ディレクトリです
log_dir = .
# ログの出力先ファイルのファイル名です
log_name = kohaku.jsonl
# ログの標準出力への出力可否の指定です
# true にした場合はファイルにログは出力されません
log_stdout = true

# ローテーションするログの最大サイズ（MB）です
#log_rotate_max_size = 200
# 保持するログファイルの最大数です
#log_rotate_max_backups = 7
# 古いログファイルを保持する最大日数です
#log_rotate_max_age = 30

postgres_uri = postgres://postgres:password@127.0.0.1:5432/kohaku
# postgres_ca_cert_file = cert/postgres/ca.pem

http2_max_concurrent_streams = 250
http2_max_read_frame_size = 1048576
http2_idle_timeout = 60
