debug = false

log_dir = "."
log_name = "kohaku.jsonl"
log_stdout = false

listen_addr = "0.0.0.0"
listen_port = 5890

exporter_listen_addr = "0.0.0.0"
exporter_listen_port = 5891

postgres_uri = "postgres://postgres:password@127.0.0.1:5432/kohaku"
# postgres_ca_cert_file = ""

http2_fullchain_file = ""
http2_privkey_file = ""
http2_verify_cacert_path = ""

http2_max_concurrent_streams = 250
http2_max_read_frame_size = 1048576
http2_idle_timeout = 60
