{
 "title": "RTC Stats",
 "time": { "from": "2025-09-19T04:42:35.000Z", "to": "2025-09-19T07:36:36.000Z" },
 "refresh": "auto",
 "templating": {
  "list": [
   { "name": "channel_id", "label": "Channel ID", "query": "sora" },
   { "name": "session_id", "label": "Session ID", "query": "W5NS0J9EBH6K59EPY7YQRB2C64" },
   {
    "name": "connection_id",
    "label": "Connection ID",
    "query": "SELECT\n  connection_id\nFROM rtc_stats\nWHERE\n  channel_id = '${channel_id}'\n  AND session_id IN ('${session_id}')\n;"
   },
   {
    "name": "inbound_rtp_audio_rtc_id",
    "label": "inbound-rtp audio RTC Stats ID",
    "query": "WITH result AS (\n  SELECT DISTINCT\n    rtc_id,\n  FROM rtc_stats\n  WHERE $__timeFilter(timestamp)\n    AND connection_id = '${connection_id}'\n    AND rtc_type = 'inbound-rtp'\n    AND (rtc_data->>'$.kind') = 'audio'\n)\nSELECT * FROM result\nUNION ALL\nSELECT ' '\nWHERE NOT EXISTS (SELECT 1 FROM result);"
   },
   {
    "name": "inbound_rtp_video_rtc_id",
    "label": "inbound-rtp video RTC Stats ID",
    "query": "WITH result AS (\n  SELECT DISTINCT\n    rtc_id,\n  FROM rtc_stats\n  WHERE $__timeFilter(timestamp)\n    AND connection_id = '${connection_id}'\n    AND rtc_type = 'inbound-rtp'\n    AND (rtc_data->>'$.kind') = 'video'\n)\nSELECT * FROM result\nUNION ALL\nSELECT ' '\nWHERE NOT EXISTS (SELECT 1 FROM result);"
   },
   {
    "name": "outbound_rtp_audio_rtc_id",
    "label": "outbound-rtp audio RTC Stats ID",
    "query": "WITH result AS (\n  SELECT DISTINCT\n    rtc_id,\n  FROM rtc_stats\n  WHERE $__timeFilter(timestamp)\n    AND connection_id = '${connection_id}'\n    AND rtc_type = 'outbound-rtp'\n    AND (rtc_data->>'$.kind') = 'audio'\n)\nSELECT * FROM result\nUNION ALL\nSELECT ' '\nWHERE NOT EXISTS (SELECT 1 FROM result);"
   },
   {
    "name": "outbound_rtp_video_rtc_id",
    "label": "outbound-rtp video RTC Stats ID",
    "query": "WITH result AS (\n  SELECT DISTINCT\n    rtc_id,\n  FROM rtc_stats\n  WHERE $__timeFilter(timestamp)\n    AND connection_id = '${connection_id}'\n    AND rtc_type = 'outbound-rtp'\n    AND (rtc_data->>'$.kind') = 'video'\n)\nSELECT * FROM result\nUNION ALL\nSELECT ' '\nWHERE NOT EXISTS (SELECT 1 FROM result);"
   }
  ]
 },
 "panels": [
  {
   "title": "inbound-rtp audio (${inbound_rtp_audio_rtc_id})",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Audio Source Panel",
     "type": "timeseries",
     "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
     "targets": [
      {
       "rawSql": "SELECT\n  time_bucket($__interval, timestamp) AS time,\n  connection_id AS connection_id,\n  rtc_id AS inbound_rtp_audio_rtc_id,\n  (rtc_data->>'$.jitter') :: double AS jitter,\n  (rtc_data->>'$.packetsLost') :: numeric AS packets_lost,\n  (rtc_data->>'$.packetsReceived') :: numeric AS packets_received,\n  (rtc_data->>'$.packetsDiscarded') :: numeric AS packets_discarded,\n  (rtc_data->>'$.fecPacketsReceived') :: numeric AS fec_packets_received,\n  (rtc_data->>'$.fecPacketsDiscarded') :: numeric AS fec_packets_discarded,\n  (rtc_data->>'$.bytesReceived') :: numeric AS bytes_received,\n  (rtc_data->>'$.headerBytesReceived') :: numeric AS header_bytes_received,\n  (rtc_data->>'$.lastPacketReceivedTimestamp') :: double AS last_packet_received_timestamp,\n  (rtc_data->>'$.jitterBufferDelay') :: double AS jitter_buffer_delay,\n  (rtc_data->>'$.jitterBufferTargetDelay') :: double AS jitter_buffer_target_delay,\n  (rtc_data->>'$.jitterBufferMinimumDelay') :: double AS jitter_buffer_minimum_delay,\n  (rtc_data->>'$.jitterBufferEmittedCount') :: numeric AS jitter_buffer_emitted_count,\n  (rtc_data->>'$.totalSamplesReceived') :: numeric AS total_samples_received,\n  (rtc_data->>'$.concealedSamples') :: numeric AS concealed_samples,\n  (rtc_data->>'$.silentConcealedSamples') :: numeric AS silent_concealed_samples,\n  (rtc_data->>'$.concealmentEvents') :: numeric AS concealment_events,\n  (rtc_data->>'$.insertedSamplesForDeceleration') :: numeric AS inserted_samples_for_deceleration,\n  (rtc_data->>'$.removedSamplesForAcceleration') :: numeric AS removed_samples_for_acceleration,\n  (rtc_data->>'$.audioLevel') :: double AS audio_level,\n  (rtc_data->>'$.totalAudioEnergy') :: double AS total_audio_energy,\n  (rtc_data->>'$.totalSamplesDuration') :: double AS total_samples_duration,\n  (rtc_data->>'$.estimatedPlayoutTimestamp') :: numeric AS estimated_playout_timestamp\nFROM\n  rtc_stats\nWHERE\n  $__timeFilter(timestamp)\n  AND connection_id IN (${connection_id})\n  AND rtc_id IN (${inbound_rtp_audio_rtc_id})\n  AND (rtc_data->>'$.type') = 'inbound-rtp'\nORDER BY\n  time\n;"
      },
      {
       "rawSql": "SELECT\n  time_bucket($__interval, t.time) AS time,\n  t.connection_id AS connection_id,\n  t.inbound_rtp_audio_rtc_id AS inbound_rtp_audio_rtc_id,\n  ((t.packets_received - lag(t.packets_received, 1, t.packets_received) OVER w) / $__interval_ms * 1000) :: numeric AS 'packetsReceived/s',\n  ((t.bytes_received - lag(t.bytes_received, 1, t.bytes_received) OVER w) / $__interval_ms * 1000 * 8) :: numeric AS 'bytesReceived_in_bits/s',\n  ((t.header_bytes_received - lag(t.header_bytes_received, 1, t.header_bytes_received) OVER w) / $__interval_ms * 1000 * 8) :: numeric AS 'headerBytesReceived_in_bits/s'\nFROM (\n  SELECT\n    timestamp AS time,\n    connection_id AS connection_id,\n    rtc_id AS inbound_rtp_audio_rtc_id,\n    (rtc_data->>'$.packetsReceived') :: numeric AS packets_received,\n    (rtc_data->>'$.bytesReceived') :: numeric AS bytes_received,\n    (rtc_data->>'$.headerBytesReceived') :: numeric AS header_bytes_received\n  FROM rtc_stats\n  WHERE\n    $__timeFilter(timestamp)\n    AND connection_id = ('${connection_id}')\n    AND (rtc_data->>'$.id') IN ('${inbound_rtp_audio_rtc_id}')\n    AND (rtc_data->>'$.type') = 'inbound-rtp'\n  ORDER BY time\n) AS t\nWINDOW w AS (PARTITION BY t.connection_id, t.inbound_rtp_audio_rtc_id ORDER BY t.time)\nORDER BY time\n;"
      }
     ]
    },
    {
     "title": "jitter",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 458 },
     "targets": [
      { "panelId": 40 }
     ]
    },
    {
     "title": "packetsLost",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 458 },
     "targets": [
      { "panelId": 40 }
     ]
    },
    {
     "title": "packetsReceived",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 458 },
     "targets": [
      { "panelId": 40 }
     ]
    },
    {
     "title": "fecPacketsReceived",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 466 },
     "targets": [
      { "panelId": 40 }
     ]
    },
    {
     "title": "packetsDiscarded",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 466 },
     "targets": [
      { "panelId": 40 }
     ]
    },
    {
     "title": "fecPacketsDiscarded",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 466 },
     "targets": [
      { "panelId": 40 }
     ]
    },
    {
     "title": "bytesReceived",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 474 },
     "targets": [
      { "panelId": 40 }
     ]
    },
    {
     "title": "jitterBufferDelay",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 474 },
     "targets": [
      { "panelId": 40 }
     ]
    },
    {
     "title": "lastPacketReceivedTimestamp",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 474 },
     "targets": [
      { "panelId": 40 }
     ]
    },
    {
     "title": "concealedSamples",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 482 },
     "targets": [
      { "panelId": 40 }
     ]
    },
    {
     "title": "jitterBufferEmittedCount",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 482 },
     "targets": [
      { "panelId": 40 }
     ]
    },
    {
     "title": "silentConcealedSamples",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 482 },
     "targets": [
      { "panelId": 40 }
     ]
    },
    {
     "title": "totalSamplesReceived",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 490 },
     "targets": [
      { "panelId": 40 }
     ]
    },
    {
     "title": "insertedSamplesForDeceleration",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 490 },
     "targets": [
      { "panelId": 40 }
     ]
    },
    {
     "title": "totalSamplesDuration",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 490 },
     "targets": [
      { "panelId": 40 }
     ]
    },
    {
     "title": "audioLevel",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 498 },
     "targets": [
      { "panelId": 40 }
     ]
    },
    {
     "title": "concealmentEvents",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 498 },
     "targets": [
      { "panelId": 40 }
     ]
    },
    {
     "title": "totalAudioEnergy",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 498 },
     "targets": [
      { "panelId": 40 }
     ]
    },
    {
     "title": "removedSamplesForAcceleration",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 506 },
     "targets": [
      { "panelId": 40 }
     ]
    },
    {
     "title": "estimatedPlayoutTimestamp",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 506 },
     "targets": [
      { "panelId": 40 }
     ]
    },
    {
     "title": "jitterBufferTargetDelay",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 506 },
     "targets": [
      { "panelId": 40 }
     ]
    },
    {
     "title": "bytesReceived_in_bits/s",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 514 },
     "targets": [
      { "panelId": 40 }
     ]
    },
    {
     "title": "packetsReceived/s",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 514 },
     "targets": [
      { "panelId": 40 }
     ]
    },
    {
     "title": "headerBytesReceived_in_bits/s",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 522 },
     "targets": [
      { "panelId": 40 }
     ]
    },
    {
     "title": "jitterBufferMinimumDelay",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 522 },
     "targets": [
      { "panelId": 40 }
     ]
    }
   ]
  },
  {
   "title": "outbound-rtp audio (${outbound_rtp_audio_rtc_id})",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 }
  },
  {
   "title": "Outbound Audio Source Panel",
   "type": "timeseries",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "targets": [
    {
     "rawSql": "SELECT\n  time_bucket($__interval, timestamp) AS time,\n  connection_id AS connection_id,\n  rtc_id AS outbound_rtp_audio_rtc_id,\n  (rtc_data->>'$.bytesSent') :: numeric AS bytes_sent,\n  (rtc_data->>'$.headerBytesSent') :: numeric AS header_bytes_sent,\n  (rtc_data->>'$.nackCount') :: numeric AS nack_count,\n  (rtc_data->>'$.packetsSent') :: numeric AS packets_sent,\n  (rtc_data->>'$.retransmittedBytesSent') :: numeric AS retransmitted_bytes_sent,\n  (rtc_data->>'$.retransmittedPacketsSent') :: numeric AS retransmitted_packets_sent,\n  (rtc_data->>'$.targetBitrate') :: double AS target_bitrate,\n  (rtc_data->>'$.totalPacketSendDelay') :: double AS total_packet_send_delay,\nFROM\n  rtc_stats\nWHERE\n  $__timeFilter(timestamp)\n  AND connection_id IN (${connection_id})\n  AND rtc_id IN (${outbound_rtp_audio_rtc_id})\n  AND (rtc_data->>'$.type') = 'outbound-rtp'\nORDER BY\n  time\n;"
    },
    {
     "rawSql": "SELECT\n  time_bucket($__interval, t.time) AS time,\n  t.connection_id AS connection_id,\n  t.outbound_rtp_audio_rtc_id AS outbound_rtp_audio_rtc_id,\n  ((t.packets_sent - lag(t.packets_sent, 1, t.packets_sent) OVER w) / $__interval_ms * 1000) :: numeric AS 'packetsSent/s',\n  ((t.bytes_sent - lag(t.bytes_sent, 1, t.bytes_sent) OVER w) / $__interval_ms * 1000 * 8) :: numeric AS 'bytesSent_in_bits/s',\n  ((t.header_bytes_sent - lag(t.header_bytes_sent, 1, t.header_bytes_sent) OVER w) / $__interval_ms * 1000 * 8) :: numeric AS 'headerBytesSent_in_bits/s'\nFROM (\n  SELECT\n    timestamp AS time,\n    connection_id AS connection_id,\n    rtc_id AS outbound_rtp_audio_rtc_id,\n    (rtc_data->>'$.packetsSent') :: numeric AS packets_sent,\n    (rtc_data->>'$.bytesSent') :: numeric AS bytes_sent,\n    (rtc_data->>'$.headerBytesSent') :: numeric AS header_bytes_sent\n  FROM rtc_stats\n  WHERE\n    $__timeFilter(timestamp)\n    AND connection_id = ('${connection_id}')\n    AND (rtc_data->>'$.id') IN ('${outbound_rtp_audio_rtc_id}')\n    AND (rtc_data->>'$.type') = 'outbound-rtp'\n  ORDER BY time\n) AS t\nWINDOW w AS (PARTITION BY t.connection_id, t.outbound_rtp_audio_rtc_id ORDER BY t.time)\nORDER BY time\n;"
    }
   ]
  },
  {
   "title": "bytesSent",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 3 },
   "targets": [
    { "panelId": 89 }
   ]
  },
  {
   "title": "headerBytesSent",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 3 },
   "targets": [
    { "panelId": 89 }
   ]
  },
  {
   "title": "nackCount",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 3 },
   "targets": [
    { "panelId": 89 }
   ]
  },
  {
   "title": "packetsSent",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 11 },
   "targets": [
    { "panelId": 89 }
   ]
  },
  {
   "title": "retransmittedBytesSent",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 11 },
   "targets": [
    { "panelId": 89 }
   ]
  },
  {
   "title": "retransmittedPacketsSent",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 11 },
   "targets": [
    { "panelId": 89 }
   ]
  },
  {
   "title": "inbound-rtp video (${inbound_rtp_video_rtc_id})",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "Video Source Panel",
     "type": "timeseries",
     "gridPos": { "h": 1, "w": 24, "x": 0, "y": 231 },
     "targets": [
      {
       "rawSql": "SELECT\n  time_bucket($__interval, timestamp) AS time,\n  connection_id AS connection_id,\n  rtc_id AS inbound_rtp_video_rtc_id,\n  (rtc_data->>'$.jitter') :: double AS jitter,\n  (rtc_data->>'$.packetsLost') :: numeric AS packets_lost,\n  (rtc_data->>'$.packetsReceived') :: numeric AS packets_received,\n  (rtc_data->>'$.bytesReceived') :: numeric AS bytes_received,\n  (rtc_data->>'$.headerBytesReceived') :: numeric AS header_bytes_received,\n  (rtc_data->>'$.lastPacketReceivedTimestamp') :: double AS last_packet_received_timestamp,\n  (rtc_data->>'$.jitterBufferDelay') :: double AS jitter_buffer_delay,\n  (rtc_data->>'$.jitterBufferTargetDelay') :: double AS jitter_buffer_target_delay,\n  (rtc_data->>'$.jitterBufferMinimumDelay') :: double AS jitter_buffer_minimum_delay,\n  (rtc_data->>'$.jitterBufferEmittedCount') :: numeric AS jitter_buffer_emitted_count,\n  (rtc_data->>'$.framesReceived') :: numeric AS frames_received,\n  (rtc_data->>'$.framesDecoded') :: numeric AS frames_decoded,\n  (rtc_data->>'$.frameWidth') :: numeric AS frame_width,\n  (rtc_data->>'$.frameHeight') :: numeric AS frame_height,\n  (rtc_data->>'$.framesPerSecond') :: numeric AS frames_per_second,\n  (rtc_data->>'$.keyFramesDecoded') :: numeric AS key_frames_decoded,\n  (rtc_data->>'$.framesDropped') :: numeric AS frames_dropped,\n  (rtc_data->>'$.totalDecodeTime') :: double AS total_decode_time,\n  (rtc_data->>'$.totalInterFrameDelay') :: double AS total_inter_frame_delay,\n  (rtc_data->>'$.totalProcessingDelay') :: double AS total_processing_delay,\n  (rtc_data->>'$.totalAssemblyTime') :: double AS total_assembly_time,\n  (rtc_data->>'$.totalSquaredInterFrameDelay') :: double AS total_squared_inter_frame_delay,\n  (rtc_data->>'$.totalPausesDuration') :: double AS total_pauses_duration,\n  (rtc_data->>'$.totalFreezesDuration') :: double AS total_freezes_duration,\n  (rtc_data->>'$.freezeCount') :: numeric AS freeze_count,\n  (rtc_data->>'$.firCount') :: numeric AS fir_count,\n  (rtc_data->>'$.pliCount') :: numeric AS pli_count,\n  (rtc_data->>'$.pauseCount') :: numeric AS pause_count,\n  (rtc_data->>'$.nackCount') :: numeric AS nack_count,\n  (rtc_data->>'$.estimatedPlayoutTimestamp') :: numeric AS estimated_playout_timestamp\nFROM\n  rtc_stats\nWHERE\n  $__timeFilter(timestamp)\n  AND connection_id IN (${connection_id})\n  AND rtc_id IN (${inbound_rtp_video_rtc_id})\n  AND (rtc_data->>'$.type') = 'inbound-rtp'\nORDER BY\n  time\n;\n"
      },
      {
       "rawSql": "SELECT\n  time_bucket($__interval, t.time) AS time,\n  t.connection_id AS connection_id,\n  t.inbound_rtp_video_rtc_id AS inbound_rtp_video_rtc_id,\n  ((t.packets_received - lag(t.packets_received, 1, NULL) OVER w) / $__interval_ms * 1000) :: numeric AS 'packetsReceived/s',\n  ((t.bytes_received - lag(t.bytes_received, 1, t.bytes_received) OVER w) / $__interval_ms * 1000 * 8) :: numeric AS 'bytesReceived_in_bits/s',\n  ((t.header_bytes_received - lag(t.header_bytes_received, 1, t.header_bytes_received) OVER w) / $__interval_ms * 1000 * 8) :: numeric AS 'headerBytesReceived_in_bits/s',\n  ((t.frames_received - lag(t.frames_received, 1, t.frames_received) OVER w) / $__interval_ms * 1000) :: numeric AS 'framesReceived/s',\n  ((t.frames_decoded - lag(t.frames_decoded, 1, t.frames_decoded) OVER w) / $__interval_ms * 1000) :: numeric AS 'framesDecoded/s',\n  ((t.key_frames_decoded - lag(t.key_frames_decoded, 1, t.key_frames_decoded) OVER w) / $__interval_ms * 1000) :: numeric AS 'keyFramesDecoded/s'\nFROM (\n  SELECT\n    timestamp AS time,\n    connection_id,\n    rtc_id AS inbound_rtp_video_rtc_id,\n    (rtc_data->>'$.packetsReceived') :: numeric AS packets_received,\n    (rtc_data->>'$.bytesReceived') :: numeric AS bytes_received,\n    (rtc_data->>'$.headerBytesReceived') :: numeric AS header_bytes_received,\n    (rtc_data->>'$.framesReceived') :: numeric AS frames_received,\n    (rtc_data->>'$.framesDecoded') :: numeric AS frames_decoded,\n    (rtc_data->>'$.keyFramesDecoded') :: numeric AS key_frames_decoded\n  FROM rtc_stats\n  WHERE\n    $__timeFilter(timestamp)\n    AND connection_id = ('${connection_id}')\n    AND (rtc_data->>'$.id') IN ('${inbound_rtp_video_rtc_id}')\n    AND (rtc_data->>'$.type') = 'inbound-rtp'\n  ORDER BY time\n) AS t\nWINDOW w AS (PARTITION BY t.connection_id, t.inbound_rtp_video_rtc_id ORDER BY t.time)\nORDER BY time\n;"
      }
     ]
    },
    {
     "title": "jitter",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 289 },
     "targets": [
      { "panelId": 3 }
     ]
    },
    {
     "title": "packetsLost",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 289 },
     "targets": [
      { "panelId": 3 }
     ]
    },
    {
     "title": "packetsReceived",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 289 },
     "targets": [
      { "panelId": 3 }
     ]
    },
    {
     "title": "headerBytesReceived",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 297 },
     "targets": [
      { "panelId": 3 }
     ]
    },
    {
     "title": "bytesReceived",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 297 },
     "targets": [
      { "panelId": 3 }
     ]
    },
    {
     "title": "jitterBufferDelay",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 297 },
     "targets": [
      { "panelId": 3 }
     ]
    },
    {
     "title": "framesReceived",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 305 },
     "targets": [
      { "panelId": 3 }
     ]
    },
    {
     "title": "lastPacketReceivedTimestamp",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 305 },
     "targets": [
      { "panelId": 3 }
     ]
    },
    {
     "title": "jitterBufferEmittedCount",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 305 },
     "targets": [
      { "panelId": 3 }
     ]
    },
    {
     "title": "frameHeight",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 313 },
     "targets": [
      { "panelId": 3 }
     ]
    },
    {
     "title": "frameWidth",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 313 },
     "targets": [
      { "panelId": 3 }
     ]
    },
    {
     "title": "framesDecoded",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 313 },
     "targets": [
      { "panelId": 3 }
     ]
    },
    {
     "title": "framesPerSecond",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 321 },
     "targets": [
      { "panelId": 3 }
     ]
    },
    {
     "title": "keyFramesDecoded",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 321 },
     "targets": [
      { "panelId": 3 }
     ]
    },
    {
     "title": "framesDropped",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 321 },
     "targets": [
      { "panelId": 3 }
     ]
    },
    {
     "title": "totalDecodeTime",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 329 },
     "targets": [
      { "panelId": 3 }
     ]
    },
    {
     "title": "totalInterFrameDelay",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 329 },
     "targets": [
      { "panelId": 3 }
     ]
    },
    {
     "title": "totalSquaredInterFrameDelay",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 329 },
     "targets": [
      { "panelId": 3 }
     ]
    },
    {
     "title": "firCount",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 337 },
     "targets": [
      { "panelId": 3 }
     ]
    },
    {
     "title": "pliCount",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 337 },
     "targets": [
      { "panelId": 3 }
     ]
    },
    {
     "title": "nackCount",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 337 },
     "targets": [
      { "panelId": 3 }
     ]
    },
    {
     "title": "bytesReceived_in_bits/s",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 345 },
     "targets": [
      { "panelId": 3 }
     ]
    },
    {
     "title": "packetsReceived/s",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 345 },
     "targets": [
      { "panelId": 3 }
     ]
    },
    {
     "title": "framesReceived/s",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 345 },
     "targets": [
      { "panelId": 3 }
     ]
    },
    {
     "title": "headerBytesReceived_in_bits/s",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 353 },
     "targets": [
      { "panelId": 3 }
     ]
    },
    {
     "title": "keyFramesDecoded/s",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 353 },
     "targets": [
      { "panelId": 3 }
     ]
    },
    {
     "title": "framesDecoded/s",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 353 },
     "targets": [
      { "panelId": 3 }
     ]
    },
    {
     "title": "jitterBufferTargetDelay",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 361 },
     "targets": [
      { "panelId": 3 }
     ]
    },
    {
     "title": "jitterBufferMinimumDelay",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 361 },
     "targets": [
      { "panelId": 3 }
     ]
    },
    {
     "title": "totalAssemblyTime",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 361 },
     "targets": [
      { "panelId": 3 }
     ]
    },
    {
     "title": "totalProcessingDelay",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 369 },
     "targets": [
      { "panelId": 3 }
     ]
    },
    {
     "title": "totalPausesDuration",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 369 },
     "targets": [
      { "panelId": 3 }
     ]
    },
    {
     "title": "pauseCount",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 369 },
     "targets": [
      { "panelId": 3 }
     ]
    },
    {
     "title": "totalFreezesDuration",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 377 },
     "targets": [
      { "panelId": 3 }
     ]
    },
    {
     "title": "freezeCount",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 377 },
     "targets": [
      { "panelId": 3 }
     ]
    },
    {
     "title": "estimatedPlayoutTimestamp",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 377 },
     "targets": [
      { "panelId": 3 }
     ]
    }
   ]
  },
  {
   "title": "outbound-rtp video (${outbound_rtp_video_rtc_id})",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "Outbound Video Source Panel",
     "type": "timeseries",
     "gridPos": { "h": 1, "w": 24, "x": 0, "y": 232 },
     "targets": [
      {
       "rawSql": "SELECT\n  time_bucket($__interval, timestamp) AS time,\n  connection_id AS connection_id,\n  rtc_id AS outbound_rtp_video_rtc_id,\n  (rtc_data->>'$.bytesSent') :: numeric AS bytes_sent,\n  (rtc_data->>'$.firCount') :: numeric AS fir_count,\n  (rtc_data->>'$.frameWidth') :: numeric AS frame_width,\n  (rtc_data->>'$.frameHeight') :: numeric AS frame_height,\n  (rtc_data->>'$.framesEncoded') :: numeric AS frames_encoded,\n  (rtc_data->>'$.framesPerSecond') :: double AS frames_per_second,\n  (rtc_data->>'$.framesSent') :: numeric AS frames_sent,\n  (rtc_data->>'$.headerBytesSent') :: numeric AS header_bytes_sent,\n  (rtc_data->>'$.hugeFramesSent') :: numeric AS huge_frames_sent,\n  (rtc_data->>'$.keyFramesEncoded') :: numeric AS key_frames_encoded,\n  (rtc_data->>'$.nackCount') :: numeric AS nack_count,\n  (rtc_data->>'$.packetsSent') :: numeric AS packets_sent,\n  (rtc_data->>'$.pliCount') :: numeric AS pli_count,\n  (rtc_data->>'$.qpSum') :: numeric AS qp_sum,\n  (rtc_data->>'$.retransmittedBytesSent') :: numeric AS retransmitted_bytes_sent,\n  (rtc_data->>'$.retransmittedPacketsSent') :: numeric AS retransmitted_packets_sent,\n  (rtc_data->>'$.targetBitrate') :: double AS target_bitrate,\n  (rtc_data->>'$.totalEncodeTime') :: double AS total_encode_time,\n  (rtc_data->>'$.totalPacketSendDelay') :: double AS total_packet_send_delay,\nFROM\n  rtc_stats\nWHERE\n  $__timeFilter(timestamp)\n  AND connection_id IN (${connection_id})\n  AND rtc_id IN (${outbound_rtp_video_rtc_id})\n  AND (rtc_data->>'$.type') = 'outbound-rtp'\nORDER BY\n  time\n;"
      },
      {
       "rawSql": "SELECT\n  time_bucket($__interval, t.time) AS time,\n  t.connection_id AS connection_id,\n  t.outbound_rtp_video_rtc_id AS outbound_rtp_video_rtc_id,\n  ((t.packets_sent - lag(t.packets_sent, 1, NULL) OVER w) / $__interval_ms * 1000) :: numeric AS 'packetsSent/s',\n  ((t.bytes_sent - lag(t.bytes_sent, 1, t.bytes_sent) OVER w) / $__interval_ms * 1000 * 8) :: numeric AS 'bytesSent_in_bits/s',\n  ((t.header_bytes_sent - lag(t.header_bytes_sent, 1, t.header_bytes_sent) OVER w) / $__interval_ms * 1000 * 8) :: numeric AS 'headerBytesSent_in_bits/s',\n  ((t.frames_sent - lag(t.frames_sent, 1, t.frames_sent) OVER w) / $__interval_ms * 1000) :: numeric AS 'framesSent/s',\n  ((t.frames_encoded - lag(t.frames_encoded, 1, t.frames_encoded) OVER w) / $__interval_ms * 1000) :: numeric AS 'framesEncoded/s',\n  ((t.key_frames_encoded - lag(t.key_frames_encoded, 1, t.key_frames_encoded) OVER w) / $__interval_ms * 1000) :: numeric AS 'keyFramesEncoded/s'\nFROM (\n  SELECT\n    timestamp AS time,\n    connection_id,\n    rtc_id AS outbound_rtp_video_rtc_id,\n    (rtc_data->>'$.packetsSent') :: numeric AS packets_sent,\n    (rtc_data->>'$.bytesSent') :: numeric AS bytes_sent,\n    (rtc_data->>'$.headerBytesSent') :: numeric AS header_bytes_sent,\n    (rtc_data->>'$.framesSent') :: numeric AS frames_sent,\n    (rtc_data->>'$.framesEncoded') :: numeric AS frames_encoded,\n    (rtc_data->>'$.keyFramesEncoded') :: numeric AS key_frames_encoded\n  FROM rtc_stats\n  WHERE\n    $__timeFilter(timestamp)\n    AND connection_id = ('${connection_id}')\n    AND (rtc_data->>'$.id') IN ('${outbound_rtp_video_rtc_id}')\n    AND (rtc_data->>'$.type') = 'outbound-rtp'\n  ORDER BY time\n) AS t\nWINDOW w AS (PARTITION BY t.connection_id, t.outbound_rtp_video_rtc_id ORDER BY t.time)\nORDER BY time\n;"
      }
     ]
    },
    {
     "title": "packetsSent",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 233 },
     "targets": [
      { "panelId": 66 }
     ]
    },
    {
     "title": "bytesSent",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 233 },
     "targets": [
      { "panelId": 66 }
     ]
    },
    {
     "title": "firCount",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 233 },
     "targets": [
      { "panelId": 66 }
     ]
    },
    {
     "title": "frameWidth",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 241 },
     "targets": [
      { "panelId": 66 }
     ]
    },
    {
     "title": "frameHeight",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 241 },
     "targets": [
      { "panelId": 66 }
     ]
    },
    {
     "title": "framesEncoded",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 241 },
     "targets": [
      { "panelId": 66 }
     ]
    },
    {
     "title": "framesPerSecond",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 249 },
     "targets": [
      { "panelId": 66 }
     ]
    },
    {
     "title": "framesSent",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 249 },
     "targets": [
      { "panelId": 66 }
     ]
    },
    {
     "title": "headerBytesSent",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 249 },
     "targets": [
      { "panelId": 66 }
     ]
    },
    {
     "title": "hugeFramesSent",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 257 },
     "targets": [
      { "panelId": 66 }
     ]
    },
    {
     "title": "keyFramesEncoded",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 257 },
     "targets": [
      { "panelId": 66 }
     ]
    },
    {
     "title": "nackCount",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 257 },
     "targets": [
      { "panelId": 66 }
     ]
    },
    {
     "title": "packetsSent",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 265 },
     "targets": [
      { "panelId": 66 }
     ]
    },
    {
     "title": "pliCount",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 265 },
     "targets": [
      { "panelId": 66 }
     ]
    },
    {
     "title": "qpSum",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 265 },
     "targets": [
      { "panelId": 66 }
     ]
    },
    {
     "title": "retransmittedBytesSent",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 273 },
     "targets": [
      { "panelId": 66 }
     ]
    },
    {
     "title": "retransmittedPacketsSent",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 273 },
     "targets": [
      { "panelId": 66 }
     ]
    },
    {
     "title": "targetBitrate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 273 },
     "targets": [
      { "panelId": 66 }
     ]
    },
    {
     "title": "totalEncodeTime",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 281 },
     "targets": [
      { "panelId": 66 }
     ]
    },
    {
     "title": "totalPacketSendDelay",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 281 },
     "targets": [
      { "panelId": 66 }
     ]
    }
   ]
  }
 ]
}