apiVersion: 1

# FYI: https://grafana.com/docs/grafana/latest/datasources/postgres/#provision-the-data-source
datasources:
- name: PostgreSQL
  type: postgres
  orgId: 1
  url: host.docker.internal:5432
  database: kohaku
  user: postgres
  secureJsonData:
    password: "password"
  jsonData:
    sslmode: "disable" # disable/require/verify-ca/verify-full
    maxOpenConns: 10
    maxIdleConns: 2
    maxIdleConnsAuto: true
    connMaxLifetime: 14400
    postgresVersion: 1500
    timescaledb: true