name: ci

on:
  workflow_dispatch:
  push:

permissions:
  contents: write


jobs:
  ci:
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v5
      - uses: astral-sh/setup-uv@v6
        with:
          enable-cache: false
      - run: |
          uv sync
        working-directory: ingester
      - run: |
          uv run pytest tests/
        working-directory: ingester
