name: ci

on:
  workflow_dispatch:
  push:

permissions:
  contents: write


jobs:
  scripts-tests:
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v6
      - uses: astral-sh/setup-uv@v8.1.0
        with:
          enable-cache: false
      - run: |
          uv run --with pytest --with testcontainers pytest -vv scripts/tests

  ci:
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v6
      - uses: astral-sh/setup-uv@v8.1.0
        with:
          enable-cache: false
      - run: |
          uv sync
        working-directory: ingester
      - run: |
          uv run pytest tests/
        working-directory: ingester
