name: ci

on:
  push:
    paths-ignore:
      - "*.md"
    branches-ignore:
      - "master"
      - "feature/clickhouse"
    tags-ignore:
      - "*"

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: setup go
        uses: actions/setup-go@v5
        with:
          go-version-file: ./go.mod
          cache: true
          cache-dependency-path: ./go.sum

      - run: go version
      - run: go fmt .

      - uses: dominikh/staticcheck-action@v1
        with:
          version: "2023.1.7"
          install-go: false

      # - name: Test
      #   run: make test

      - name: Test
        run: go test -run TestDummy

      - name: Build
        run: make
